# Generated by Django 3.0.5 on 2020-04-05 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('info', models.TextField()),
            ],
            options={
                'verbose_name': '用户表',
            },
        ),
    ]
